services:
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"

  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NUXT_HOST: "0.0.0.0"
      NUXT_PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev